export const ACTION = {
  GET_STAFF_LIST: "GET_STAFF_LIST",
  STAFF_LIST_LOADING: "STAFF_LIST_LOADING",
  STAFF_LIST_FAILED: "STAFF_LIST_FAILED",

  ADD_NEW_STAFF: "ADD_NEW_STAFF",

  GET_DEPM_LIST: "GET_DEPM_LIST",
  DEPM_LIST_LOADING: "DEPM_LIST_LOADING",
  DEPM_LIST_FAILED: "DEPM_LIST_FAILED",

  GET_SALARY_LIST: "GET_SALARY_LIST",
  SALARY_LIST_LOADING: "SALARY_LIST_LOADING",
  SALARY_LIST_FAILED: "SALARY_LIST_FAILED",
};
