export const ACTION = {
  GET_STAFF_LIST: "GET_STAFF_LIST",
  STAFF_LIST_LOADING: "STAFF_LIST_LOADING",
  STAFF_LIST_FALED: "STAFF_LIST_FALED",

  ADD_NEW_STAFF: "ADD_NEW_STAFF",

  GET_DEPM_LIST: "GET_DEPM_LIST",
  DEPM_LIST_LOADING: "DEPM_LIST_LOADING",
  DEPM_LIST_FALED: "DEPM_LIST_FALED",
};
